name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
  # Run every Monday and Wednesday at 22:10
    - cron: '10 22 * * 1'
    - cron: '10 22 * * 3'
  pull_request:
    branches: [ "main" ]

jobs:
  tests_e2e:
    name: UI and API tests
    # TEMP: Pin to ubuntu-22.04 because Playwright --with-deps fails on ubuntu-24.04
    # TODO: Change back to 'ubuntu-latest' once Playwright fixes Ubuntu 24.04 support
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm ci
        
      - name: Install playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run tests
        run: npx playwright test
            
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
            SLACK_USERNAME: Tests execution report
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: autotest_boilerplates
            SLACK_COLOR: ${{ job.status }}
            SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            SLACK_TITLE: TypeScript + Playwright
            MSG_MINIMAL: true
            SLACK_FOOTER: boilerplate
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30